# Generated by Django 4.2.3 on 2024-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='adposter',
            name='description',
            field=models.TextField(default='ad'),
            preserve_default=False,
        ),
    ]
