# Generated by Django 4.2.3 on 2024-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_adposter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adposter',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
