# Generated by Django 4.2.8 on 2024-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_appuser_subscription_alter_adposter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_advertiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
