# Generated by Django 4.2.8 on 2024-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0005_appuser_is_advertiser_appuser_is_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
