# Generated by Django 4.2.3 on 2024-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0005_adposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='adposter',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
